spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    hikari: 
      connection-test-query: SELECT 1
  jpa:
    show-sql: false

server:
  servlet:
    context-path: /throttle
 
management:
  endpoints:
    web:
      base-path: /monitor
  endpoint: 
    health: 
      show-details: always

use:
  distributed: true